version: '{build}'
init:
- ps: |
    # The $env:PATH is way too long; try to reduce it a bit.
    # src.: https://gist.github.com/wget/a102f89c301014836aaa49a98dd06ee2
    Write-Host "This is the path: $env:path"
    Write-Host "Reducing too long PATH by removing all the stuff added in Program Files except Git"
    [array]$newPath=($env:path -split ';') | Where-Object { $_ -notlike "C:\Program Files*"}
    $newPath += ($env:path -split ';') | Where-Object { $_ -like "C:\Program Files*\*Git*"}
    $env:path = $newPath -join ';'
    [Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Machine)
    [Environment]::SetEnvironmentVariable("INCLUDE", $env:INCLUDE, [System.EnvironmentVariableTarget]::User)
    Write-Host "This is the new path: $env:path"
    Write-Host "Installing AU..."
    choco install au --yes
clone_script:
- ps: |
    # The git process needs to be used with Start-Process when PS is used,
    # otherwise the parsing of the arguments will fail.
    Write-Host "Current working directory: $(Get-Location)"
    Start-Process -FilePath "git" -ArgumentList "config --global url.https://github.com/wget/chocolatey.insteadOf git@github.com:wget/chocolatey" -NoNewWindow -Wait -Passthru
    Start-Process -FilePath "git" -ArgumentList "clone --recursive git@github.com:wget/chocolatey-package-openvpn.git openvpn" -NoNewWindow -Wait -Passthru
nuget:
  disable_publish_on_pr: true
build_script:
- ps: |
    Write-Host "Current working directory: $(Get-Location)"
    Write-Host "In the current working directory: $(Get-ChildItem)"
    Write-Host "Changing directory..."
    cd openvpn
    Write-Host "Current working directory: $(Get-Location)"
    Write-Host "In the current working directory: $(Get-ChildItem)"
    # For some reason $au_NoCheckUrl = $au_Force = $true; Update-Package was
    # not downloading the files but was just creating the nupkg file.
    # Had to use the "update" alias instead to make it work.
    $au_NoCheckUrl = $au_Force = $true; update
test: off
artifacts:
- path: openvpn\*.nupkg
deploy: off
notifications:
- provider: Email
  to:
  - william+chocolatey@gathoye.be
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
on_success:
- ps: |
    Write-Host "Current working directory: $(Get-Location)"
    Write-Host "In the current working directory: $(Get-ChildItem)"
    $xml = [xml](Get-Content .\openvpn.nuspec)
    choco install openvpn -fdvy -source "'.;https://chocolatey.org/api/v2/'" --version $xml.package.metadata.version
    choco uninstall openvpn -dvy

# Please uncomment to have a RDP session, particularly useful to debug
# src.: https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
